---
title: "Bellabeat Case Study"
author: "Bishop Sally"
date: "2023-06-01"
output: html_document
---

# **Introduction** 

This is my breakdown of my Bellabeat Case study capstone project, which is part of my Google Data Analytics Certificate. This breakdown will give general insights to the analyst team at Bellabeat to make informed business decisions that can help the company in the future
The method I used to analyze Bellabeat was breaking everything down by using:

ASK 
PREPARE
PROCESS
ANALYZE
SHARE
ACT

## **About Bellabeat**

[Bellabeat](https://bellabeat.com/?gclid=CjwKCAjwg-GjBhBnEiwAMUvNW8dU3gg_7xVeMp_WV-1Acp6kc_57Kj7kPTRdLJCLFy2Cq3PRWln7cRoCep0QAvD_BwE) is a high-tech manufacturer of health-focused products for women. Bellabeat is a successful small company, but they have the potential to become a larger player in the global smart device market. Urška Sršen, cofounder and Chief Creative Officer of Bellabeat, believes that analyzing smart device fitness data could help unlock new growth opportunities for the company.

# **Ask**  
In the *Ask* section we should ask some key questions to find the problem and how we can solve them. The key questions that need to be asked to gain further insight are:
  **1.** What are the trends of smart device usuage?
  **2.** How can these trends apply to Bellabeat Customers?
  **3.**  How can these trends help influence Bellabeat Marketing Strategy 

**Business Task:** The questions that need to be asked will lead us to analyze smart device usage to gain insight into how consumers use non-Bellabeat smart devices. After we gain the insights we need we will then select one Bellabeat product that we can apply to these insights.

**How I will report the information:**
1. Give a clear summary of the business task
2. Adding a description of all data sources used
3. Documenting any cleaning or manipulation of data
4. Providing a summary of my analysis
5. Supporting visualizations and key findings
6. Your top high-level content recommendations based on your analysis

**Identifying Key Stakeholders:**
  *__Primary StakeHolders:__
  - **Urška Sršen:** Bellabeat’s cofounder and Chief Creative Officer
  - **Sando Mur:** Mathematician and Bellabeat’s cofounder; key member of the Bellabeat executive team
  Secondary Stakeholders:
  *__Secondary Stakeholders:__
  - **Bellabeat marketing analytics team:** A team of data analysts responsible for collecting, analyzing, and reporting data that helps guide Bellabeat’s marketing strategy

# **Prepare**

* __What data was gathered:__
  [*Kaggle Dataset](https://www.kaggle.com/datasets/arashnic/fitbit) 
  *	This dataset was generated by respondents to a distributed survey via [Amazon Mechanical Turk](https://zenodo.org/record/53894#.YMoUpnVKiP9) between 03.12.2016-05.12.2016. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring.
* __Data Summary__:
  - 33 Fitbit users agreed to submit personal data while using their Fitbit Trackers.The data tracked contained different factors for each dataset
  - There is a total of 18 csv files that were used for the [FitBit Fitness Tracker Data](https://www.kaggle.com/datasets/arashnic/fitbit). Out of the 18, I used 8 out of the 18 datasets to help me find a solution. These datasets included: *daily_activity*, *daily_calories*, *daily_intensities*, *daily_steps*, *hourly_calories*, *hourly_steps*,*sleep_day*, and *weight_info*.
  - The data was generated between March 12 2016 through May 12 2016 
  - Source: Furberg, R., Brinton, J., Keating, M., & Ortiz, A. (2016). Crowd-sourced Fitbit datasets 03.12.2016-05.12.2016 [Data set]. Zenodo. https://doi.org/10.5281/zenodo.53894
  - [Creative Commons Atrribution 4.0 International](https://creativecommons.org/licenses/by/4.0/legalcode)

## **Data Reliability**
- 33 participants is considered a sufficent sample size, but a larger sample size would be more efficient based on the market size of the fitness tracker market as a whole. 
- The participants are also anonymous so it does not include specifc demogrpahic data to avoid any biases. 
- The data tracked activtiy and correlation but it does not state any specific features being utilized and tracked during this study.
- The data was genereated between March and May 2016, so this data can be considered old and not being up to date with newer trends and features of Fitness Trackers

## **Conclusion:** I think overall this data is sufficient enough to get a general consensus of the Fitness tracker market, but a larger and more current data set would be a good alternative in the future.

# **Process**
The data sets were downloaded and saved into a secure folder to keep the information organized and safe. This made my processing very effiecient

```{r}
# Installing and loading necessary packages

install.packages("tidyverse")
install.packages("ggplot2")
install.packages("janitor")
install.packages("lubridate")

```

```{r}
library(tidyverse)
library(ggplot2)
library(janitor)
library(lubridate)
library(dplyr)
library(readr)

```

```{r}
library(ggplot2)
library(janitor)

```